name: CI

on:
  push:
      branches: [develop]
  pull_request:
      branches: [develop]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          pwd
          curl -LO https://nightly.link/iina-plus/homebrew-mpv-iina/actions/runs/1790379856/deps.zip
          unzip -d deps deps

      - name: Archive
        run: make archive

      - name: Create dmg
        run: brew install create-dmg && make dmg

      - uses: actions/upload-artifact@v2
        with:
          name: IINA
          path: ./iina.dmg
