name: CI

on:
  push:
      branches: [develop]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          brew update
          cp other/*-iina.rb $(brew --repo homebrew/core)/Formula
          brew install create-dmg

      - name: Install dependencies
        run: make depends

      - name: Build
        run: make build

      - uses: actions/upload-artifact@v2
        with:
          name: IINA
          path: IINA.dmg
